UI/WebStore/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using WebStore.Domain.Entities.Identity;
using WebStore.Interfaces.Services;
using WebStore.Domain.Models;
using WebStore.Domain.ViewModels;

namespace WebStore.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly IEmployeesData _employeesData;

        public EmployeesController(IEmployeesData employeesData)
        {
            _employeesData = employeesData;
        }

        public IActionResult Index() => View(_employeesData.Get());

        public IActionResult Details(int Id)
        {
            var model = _employeesData.Get(Id);

            if (model is not null)
                return View(model);

            return NotFound();
        }

        [Authorize(Roles = Role.Administrator)]
        public IActionResult Create() => View("Edit", new EmployeeViewModel());

        #region Edit
        [Authorize(Roles = Role.Administrator)]
        public IActionResult Edit(int Id)
        {
            if (Id <= 0)
            {
                return BadRequest();
            }

            var employee = _employeesData.Get(Id);
            if (employee is null)
            {
                return NotFound();
            }

            return View(new EmployeeViewModel
            {
                Id = employee.Id,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                MiddleName = employee.Patronymic,
                BirthDate = employee.BirthDate,
                City = employee.City,
                HireDate = employee.HireDate
            });
        }


        [HttpPost]
        [Authorize(Roles = Role.Administrator)]
        public IActionResult Edit(EmployeeViewModel model)
        {
            _ = model ?? throw new ArgumentNullException();

            var employee = new Employee
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Patronymic = model.MiddleName,
                BirthDate = model.BirthDate,
                City = model.City,
                HireDate = model.HireDate
            };

            if (employee.Id == 0)
            {
                _employeesData.Add(employee);
            }
            else
            {
                _employeesData.Update(employee);
            }

            return RedirectToAction("Index");
        }
        #endregion


        #region Delete
        [Authorize(Roles = Role.Administrator)]
        public IActionResult Delete(int Id)
        {
            if (Id <= 0)
            {
                return BadRequest();
            }

            var employee = _employeesData.Get(Id);
            if (employee is null)
            {
                return NotFound();
            }

            return View(new EmployeeViewModel
            {
                Id = employee.Id,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                MiddleName = employee.Patronymic,
                BirthDate = employee.BirthDate,
                City = employee.City,
                HireDate = employee.HireDate
            });
        }


        [HttpPost]
        [Authorize(Roles = Role.Administrator)]
        public IActionResult DeleteConfirmed(int Id)
        {
            _employeesData.Delete(Id);
            return RedirectToAction("Index");
        }
        #endregion

    }
}

UI/WebStore/Views/Employees/Delete.cshtml
@model EmployeeViewModel

@{
    Layout = "_LayoutEmployees";
    ViewData["Title"] = "Delete";
}

<h1>Удаление сотрудника</h1>

<h3>Вы уверены, что хотите удалить этого сотрудника?</h3>
<div>    
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed" asp-route-id="@Model.Id">
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Отменить</a>
    </form>
</div>

UI/WebStore/Views/Employees/Details.cshtml
@model WebStore.Domain.Models.Employee

@{ 
    Layout = "_LayoutEmployees";
    ViewBag.Title = "Details"; 
}


<h4>Детальная информация по сотруднику:</h4>
<hr />
<table class="table">
    <tbody>
        <tr>
            <td>Id сотрудника:</td>
            <td>@Model.Id</td>
        </tr>
        <tr>
            <td>Фамилия:</td>
            <td>@Model.LastName</td>
        </tr>
        <tr>
            <td>Имя:</td>
            <td>@Model.FirstName</td>
        </tr>
        <tr>
            <td>Отчество:</td>
            <td>@Model.Patronymic</td>
        </tr>
        <tr>
            <td>Дата рождения:</td>
            <td>@Model.BirthDate.ToShortDateString()</td>
        </tr>
        <tr>
            <td>Возраст:</td>
            <td>@Model.Age</td>
        </tr>
        <tr>
            <td>Дата найма:</td>
            <td>@Model.HireDate.ToShortDateString()</td>
        </tr>
        <tr>
            <td>Город проживания:</td>
            <td>@Model.City</td>
        </tr>
    </tbody>
</table>
<hr />

@if (User.IsInRole(Role.Administrator))
{
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Редактировать</a>
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Удалить</a>
}

<hr />
<a asp-controller="Employees" asp-action="Index">Назад к списку</a>
<hr />

UI/WebStore/Views/Employees/Edit.cshtml
@model EmployeeViewModel

@{
    Layout = "_LayoutEmployees";
    ViewData["Title"] = "Edit";
}

<h4>@((Model.Id == 0) ? "Создание нового" : "Редактирование") сотрудника</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

UI/WebStore/Views/Employees/Index.cshtml
@model IEnumerable<Employee>

@{ Layout = "_LayoutEmployees"; }

<h3>Сотрудники:</h3>
<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Возраст</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.Id</td>
                <td>@employee.LastName</td>
                <td>@employee.FirstName</td>
                <td>@employee.Patronymic</td>
                <td>@employee.Age</td>
                <td>
                    <a asp-action="Details" asp-route-id="@employee.Id">
                        <i class="fa fa-info-circle"></i>
                    </a>
                    @if (User.IsInRole(Role.Administrator))
                    {
                        @:|
                        <a asp-action="Edit" asp-route-id="@employee.Id"><i class="fa fa-edit"></i> </a>@:|
                        <a asp-action="Delete" asp-route-id="@employee.Id"><i class="fa fa-trash-o"></i> </a>
                    }
                </td>
            </tr>
         }
    </tbody>
</table>
<hr>

@if (User.IsInRole(Role.Administrator))
{
    <a asp-action="Create" class="btn btn-success">Новый сотрудник</a>
    <hr />
}

<a asp-controller="Home" asp-action="Index">Домой</a>
<hr>

UI/WebStore/Views/Employees/_LayoutEmployees.cshtml
@{ 
    Layout = "_Layout";
}

<div class="container">
    @RenderBody()
</div>